name = "aotd-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"
node_compat = true

# Bindings
[[d1_databases]]
binding = "DB"
database_name = "aotd-database"
database_id = "9c38a512-48ba-447a-922b-1504f8f69f0e"

# All Apple Sign-in secrets are now stored securely via wrangler secret put
# APPLE_TEAM_ID, APPLE_CLIENT_ID, APPLE_KEY_ID, APPLE_PRIVATE_KEY

# Secrets (set these with wrangler secret put)
# APPLE_PRIVATE_KEY - Your Apple private key for Sign in with Apple
